config/routes.rb
PhishingFramework::Application.routes.draw do

	devise_for :admins

	# image tracking routes.
	get '/reports/image/:uid.png' => 'reports#image'

	# only allow emails to be send from POST request
	post '/email/preview_email/:id' => 'email#preview', as: 'preview_email'
	post '/email/test_email/:id' =>    'email#test', as: 'test_email'
	post '/email/launch_email/:id' =>  'email#launch', as: 'launch'

	# only allow deletion from POST requests
	get '/campaigns/delete_smtp_entry/:id' => 'campaigns#list'

	get "reports/list"
	get "reports/show"
	get "reports/delete"

	get "tools/emails" => "tools#emails"
	get "tools/show_emails/:id" => "tools#show_emails", as: 'show_emails'
	post "tools/enumerate_emails" => "tools#enumerate_emails"
	delete "tools/emails/:id" => "tools#destroy_email", as: 'destroy_email'
	get "tools/download_emails/:id" => "tools#download_emails", as: "download_emails"
	get "tools/import_emails" => "tools#import_emails"

	resources :campaigns do
		collection do
			get 'options'
			get 'home'
			get 'list'
			get 'aboutus'
			get 'victims'
			delete 'destroy'
		end
		member do
			post 'update_settings'
			post 'clear_victims'
		end
	end

	resources :blasts, only: [:show], shallow: true

	resources :templates do
		collection do
			get 'list'
			get 'restore'
			get 'edit_email'
			get 'update_attachment'
			delete 'destroy'
		end
	end

	resources :reports do
		collection do
			get 'list'
			get 'stats'
			get 'results'
			get 'download_logs'
			get 'download_stats'
			get 'apache_logs'
			get 'smtp'
			get 'passwords'
			post 'results'
			delete 'clear'
		end
		member do
			get 'download_excel'
		end
	end

	resources :admin do
		collection do
			get 'list'
			get 'global_settings'
			put 'update_global_settings'
		end
		member do
			get 'logins'
			post 'approve'
			post 'revoke'
			delete 'destroy'
		end
	end

  resources :clones do
  	member do
  		get 'download'
  		get 'preview'
  	end
  end

  resources :tools

	root :to => 'campaigns#home'

	match 'access', :to => 'access#menu', as: 'access'

	require 'sidekiq/web'

	authenticate :admin do
		mount Sidekiq::Web => '/sidekiq'
	end

	require 'sidekiq/api'
	match "queue-status" => proc { [200, {"Content-Type" => "text/plain"}, [Sidekiq::Queue.new.size < 100 ? "OK" : "UHOH" ]] }

	mount LetterOpenerWeb::Engine, at: 'letter_opener'

	match ':controller(/:action(/:id))(.:format)'
end

app/models/clone.rb
class Clone < ActiveRecord::Base
  attr_accessible :name, :page, :url
end

app/controllers/clones_controller.rb
class ClonesController < ApplicationController
  # GET /clones
  # GET /clones.json
  def index
    @clones = Clone.page(params[:page]).per(25).reverse_order
    @clone = Clone.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clones }
    end
  end

  # GET /clones/1
  # GET /clones/1.json
  def show
    @clone = Clone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clone }
    end
  end

  # GET /clones/new
  # GET /clones/new.json
  def new
    @clone = Clone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clone }
    end
  end

  # GET /clones/1/edit
  def edit
    @clone = Clone.find(params[:id])
  end

  # POST /clones
  # POST /clones.json
  def create
    @clone = Clone.new(params[:clone])

    # run the cloning magic
    page, code = clone_website(params[:clone])

    # ensure we got returned a page and status code
    return if page.nil? or code.nil?

    @clone.page = page
    @clone.status = code

    respond_to do |format|
      if @clone.save
        format.html { redirect_to clones_path, notice: 'Clone was successfully created.' }
        format.json { render json: @clone, status: :created, location: @clone }
      else
        format.html { render action: "new" }
        format.json { render json: @clone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clones/1
  # PUT /clones/1.json
  def update
    @clone = Clone.find(params[:id])

    respond_to do |format|
      if @clone.update_attributes(params[:clone])
        format.html { redirect_to @clone, notice: 'Clone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @clone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clones/1
  # DELETE /clones/1.json
  def destroy
    @clone = Clone.find(params[:id])
    @clone.destroy

    respond_to do |format|
      format.html { redirect_to clones_url, notice: 'Website Deleted' }
      format.json { head :no_content }
    end
  end

  def download
    clone = Clone.find(params[:id])
    send_data clone.page, filename: clone.url.parameterize + '.html'
  end

  def preview
    @clone = Clone.find(params[:id])
    render layout: false
  end

  private

  def clone_website(clone)
    agent = Mechanize.new
    agent.user_agent_alias = 'Mac Firefox'
    begin
      page = agent.get clone[:url]
    rescue ArgumentError => e
      redirect_to clones_path, notice: "ArgumentError: #{e}"
      return
    rescue Net::HTTP::Persistent::Error => e
      redirect_to clones_path, notice: "HTTP Issue: #{e}"
      return
    rescue Errno::ECONNRESET => e
      redirect_to clones_path, notice: "Connection Reset: #{e}"
      return
    rescue => e
      redirect_to clones_path, notice: "Issue: #{e}"
      return
    end

    doc = Nokogiri::HTML(page.content)
    doc.css("a").each do |link|
      if link.attributes['href']
        if link.attributes['href'].value[0].eql?('/')
          link.attributes['href'].value = "#{params[:clone][:url]}#{link.attributes['href'].value}"
        end
      end
    end

    doc.css("img").each do |image|
      if image.attributes['src']
        if image.attributes['src'].value[0].eql?('/')
          image.attributes['src'].value = "#{params[:clone][:url]}#{image.attributes['src'].value}"
        end
      end
    end

    return doc.to_s, page.code
  end
end

app/helpers/clones_helper.rb
module ClonesHelper
end

app/views/clones/_form.html.erb
<%= form_for(@clone) do |f| %>
  <% if @clone.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@clone.errors.count, "error") %> prohibited this clone from being saved:
      </h2>

      <ul>
      <% @clone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, placeholder: 'company xyz', 
          required: true, class: 'form-control' %><br>
  </div>
  <div class="field">
    <%= f.label :url, "URL:" %><br />
    <%= f.text_field :url, placeholder: 'http://www.domain.net', 
          required: true, class: 'form-control',
          pattern: "^https?\://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(/\S*)?$" %>
  </div><br>
  <div class="actions">
    <%= f.submit 'Clone Website', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clones/edit.html.erb
<h1>Editing clone</h1>

<%= render 'form' %>

<%= link_to 'Show', @clone %> |
<%= link_to 'Back', clones_path %>

app/views/clones/index.html.erb
<% @page_title = "Website Cloner" %>

<h2>Websites Cloned</h2>
<hr>

<div id="new-clone-button">
  <button class="btn btn-primary" data-toggle="modal" data-target="#newClone">
    <span class="glyphicon glyphicon-magnet"></span> Clone Website
  </button>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Status</th>
      <th><div class="pull-right">Actions</div></th>
    </tr>
  </thead>

  <tbody>
    <% @clones.each do |clone| %>
    <tr>
      <td><%= clone.name %></td>
      <td><%= truncate(clone.url) %></td>
      <td><%= clone.status %></td>
      <td>
        <div class="pull-right">
          <%= link_to '<span class="glyphicon glyphicon-search"></span>'.html_safe,
                preview_clone_path(clone), target: '_blank', 
                class: 'btn btn-xs btn-default', title: 'Preview',
                rel: 'tooltip', data: {placement: 'bottom'} %>
          <%= link_to '<span class="glyphicon glyphicon-download-alt"></span>'.html_safe,
                download_clone_path(clone), class: 'btn btn-xs btn-default', 
                title: 'Download',rel: 'tooltip', 
                data: {placement: 'bottom'} %>
          <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                clone, method: :delete, 
                data: { confirm: 'Are you sure?', placement: 'bottom' },
                class: 'btn btn-xs btn-danger', title: 'Delete',
                rel: 'tooltip' %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right">
  <%= paginate @clones, :theme => 'twitter-bootstrap-3' %>
</div>

<!-- Modal -->
<div class="modal fade" id="newClone" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-magnet"></span> Clone Website</h4>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/clones/new.html.erb
<h1>New clone</h1>

<%= render 'form' %>

app/views/clones/preview.html.erb
<%= render :inline => @clone.page %>

app/views/clones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @clone.name %>
</p>

<p>
  <b>URL:</b>
  <%= @clone.url %>
</p>

<p>
  <b>Page:</b>
  <%= render :inline => @clone.page %>
</p>

<%= link_to 'Edit', edit_clone_path(@clone) %> |
<%= link_to 'Back', clones_path %>